# Template maven-build

# This template allows you to test and build your Java project with Maven.
# The workflow allows running tests, code checkstyle, and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: markhobson/maven-chrome

trigger:
  branches:
    include:
      - master

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - mvn clean verify "-Dcucumber.filter.tags=@Sanity"
            artifacts:
              - target/report.html
              - target/TestReport/**
            after-script:
              # Collect checkstyle results and convert to Bitbucket Code Insights.
              - pipe: atlassian/checkstyle-report:0.3.0
                # Send email notification
              - pipe: atlassian/email-notify:0.13.1
                variables:
                  USERNAME: 'apikey'
                  PASSWORD: $SENDGRID_API_KEY
                  FROM: 'support@proshort.ai'
                  TO: 'naveen.g@stagsoftware.com, bharat.v@stagsoftware.com'
                  HOST: 'smtp.sendgrid.net'
                  SUBJECT: 'Bitbucket Pipeline Execution Summary'
                  ATTACHMENTS: 'target/report.html'
                  PORT: 587
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1

definitions:
  services:
    chrome:
      image: selenium/standalone-chrome