package Supports;

import java.io.File;

public class Constants {
    public final static File testDataDir = new File("TestData");
    public final static int pollingInterval1Sec = 1;
    public final static int pollingInterval2Sec = 2;
    public final static int waitTime60Sec = 60;
    public final static int waitTime90Sec = 90;
    public final static int waitTime120Sec = 120;
    public final static int waitTime200Sec = 200;
    public final static int waitTime5000MillSec = 5000;
    public final static int waitTime3000MillSec = 3000;
    public final static String excelFilePath = "Sample_Invite.csv";
    public final static File excelFileDir = new File("Sample_Invite.csv");
    public final static String uploadExcelFilePath = excelFileDir.getAbsolutePath();
    public final static String description = " is created for demo purpose";
    public final static int waitTime10000MillSec = 10000;
    public final static String imagePath = testDataDir.getAbsolutePath()+"/Image1.jpg";
    public final static String filePath = testDataDir.getAbsolutePath()+"/video_20240408111805.mp4";
    public final static String attachVideoTitle = "Attach a video";
    public final static String addVideoName = " video";
    public final static String quizModule = "Name of module";
    public final static String addQuizName = " quiz";
    public final static String quizQuestion = "Why proshort is used for?";
    public final static String quizOption1 = "To maintain collaboration";
    public final static String quizOption2 = "To obtain good knowledge";
    public final static String confirmMessage = "Are you sure?";
    public final static String activatedMsg = " activated successfully";
    public final static String deactivatedMsg = " deactivated successfully";
    public final static String updatedMsg = " updated successfully";
    public final static String pollQuestion = "What is your preferred method of transportation?";
    public final static String pollOption1 = "Car";
    public final static String pollOption2 = "Bicycle";
    public final static String url = "https://staging.proshort.ai/home";
    public final static String urlLabel = "proshort";
    public final static String createdSuccessfully = " created succesfully!";
    public final static String createdSuccessfullyForPolls = "Poll created successfully";
    public final static String updatedSuccessfully = " updated succesfully!";
    public final static String updatedSuccessfullyForPolls = "your changes have been successfully saved";
    public final static String deactivatedSuccessfully = " Deactivated";
    public final static String deactivatedSuccessfullyForPolls= " is deactivated";
    public final static String manageVideoPageTitle = "Manage Videos";
    public final static String contentSuccessMsg = "Content Uploaded Successfully";
    public final static String salesBotSuccessMsg = "Content sent for indexing";
    public final static String memberDetailsUpdateConfirmMsg = "Member details updated successfully";
    public final static String alreadyExitErrorMsg = " name already exists.";
    public final static String renamedMsg = " renamed successfully";
    public final static String groupDeactivateMsg = " deleted successfully";
    public final static String inviteSuccessMsg = "Invitation sent successfully to ";
    public final static String approveMsg = "Video Approved";
    public final static String blockMsg = "Video Blocked";
    public final static String popUpMsgForWorkSpace ="Details Updated Successfully";
    public final static String videoDescription = "Testing video";
    public final static String savedVideoMsg ="Video Uploaded";
    public final static String deletePopUpMsg = "Video has been deleted.";
    public final static String afterAnsweredQa ="Response added successfully";
    public final static String tagSavedMessage = "Your item has been saved";
    public final static String tagRemovedMessage = "Your item has been removed from saved";
    public final static String cmdMessage = "video is good";
    public final static int waitTime300MillSec = 300;
    public final static String salesBotQues ="Can you give me the brief description of uploaded content?";
    public final static String uploadContentMsg = "Content Uploaded Successfully";
    public final static String QAMsg ="Your sales bot is being generated. We'll notify you by email when it's ready!";
}
